[workspace]

resolver = "2"

members = [
    "example-dex-subintent",
    "example-flash-liquidity-subintent",
    "sdk/anthic-client",
    "sdk/anthic-model",
    "sdk/anthic-subintents",
    "sdk/anthic-trade-api-client",
]
