[package]
name = "anthic-trade-api-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.107"
serde = { version = "1.0.190", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.32.0", features = ["full"]}